Storage:
  IndexFile: ./data/wiki_index
  DumpFile: ./data/enwiki-latest-abstract1.xml.gz
BM25:
  K1: 2
  B: 0.75
Server:
  Host:
  Port:
Cluster:
  ShardingNum: 10
  ReplicateNum: 3
  ManageServer:
    Host: 127.0.0.1
    Port: 1234